### ISSUE TITLE
Preparing obj

### ISSUE THREAD

**Issue by 0xAVX** [ands/lightmapper#4]
Hello! :) How I can prepare my obj without separately indexed vertex attributes with UVAtlasTool?

Thank You)

**Comment by ands** [comment]
Hi,
not sure if I understand you correctly...
If this is a question about the usage of uvatlas, then you should probably ask it [there](https://github.com/Microsoft/UVAtlas) since I have not really used it myself.
If you have problems loading your own OBJ files with the example application, you could use a real OBJ file loader like [yocto_obj.h](https://github.com/xelatihy/yocto-gl) or switch to the development branch which already does that. But I'm not sure if the current state there works on other machines.

If I did not understand you correctly, it would help if you explained a bit more :)

**Comment by 0xAVX** [comment]
Thank you for the help!!!! )))) yocto_obj.h is what i need)
